version: "3"

services:

  backend:
    restart: unless-stopped
    container_name: backend
    build:
      context: ./Ladder-Backend
    ports:
      - 5123:5123
    volumes:
      - ./Ladder-Backend/:/Ladder-Backend/
    environment:
      FLASK_DEBUG: 1 
    command: gunicorn -w 1 -b 0.0.0.0:5123 app:app --reload
