version: "3"

services:
  frontend:
    container_name: ladder-frontend
    build:
      context: ./Ladder-Frontend
    ports:
      - 8080:8080
    volumes:
      - ./Ladder-Frontend/:/Ladder-Frontend

  backend:
    restart: unless-stopped
    container_name: backend
    build:
      context: ./Ladder-Backend
    ports:
      - 5123:5123
    volumes:
      - ./Ladder-Backend/:/Ladder-Backend/
    environment:
      FLASK_DEBUG: 1 
    command: gunicorn -w 1 -b 0.0.0.0:5123 app:app --reload 
  
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --port 6379
    labels:
      - "name=redis"
      - "mode=standalone"

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
        - postgres:/var/lib/postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 8088:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      
      
volumes:
    postgres:


