version: "3"

services:

  backend:
    restart: unless-stopped
    container_name: backend
    build:
      context: ./Ladder-Backend
    ports:
      - 5001:5001
    volumes:
      - ./Ladder-Backend/:/Ladder-Backend/
    environment:
      FLASK_DEBUG: 1 
    command: gunicorn -w 1 -b backend:5001 app:app --reload

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=ladderdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0829
    volumes:
      - postgres:/var/lib/postgres



volumes:
    postgres:
