version: "3"

services:
  frontend:
    container_name: Ladder-frontend
    build:
      context: ./Ladder-Frontend
    ports:
      - 8080:8080
    volumes:
      - ./Ladder-Frontend/:/Ladder-Frontend

  backend:
    # restart: unless-stopped
    container_name: Ladder-backend
    build:
      context: ./Ladder-Backend
    ports:
      - 5123:5123
    volumes:
      - ./Ladder-Backend/:/Ladder-Backend/
    environment:
      FLASK_DEBUG: 1 
    command: gunicorn -w 1 -b 0.0.0.0:5123 app:app --reload

  postgres:
    container_name: Ladder-postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
        - postgres:/var/lib/postgres

  pgadmin:
    container_name: Ladder-pgadmin
    image: dpage/pgadmin4
    ports:
      - 8088:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: Ladder-prometheus
    ports:
      - 9090:9090
    networks:
      - promnet

  grafana:
    image: grafana/grafana
    container_name: Ladder-grafana
    ports:
      - 3001:3001
    volumes:
      - ./grafana/grafana-volume:/var/lib/grafana
    networks:
      - promnet

networks:
  promnet:
    driver: bridge

  
      
      
volumes:
    postgres:


